### ISSUE TITLE
`BigInt.wadExpN` is returning incoherent results

### ISSUE THREAD

**Issue by oumar-fall** [Rubilmax/ethers-maths#6]
## Current Behavior

`BigInt.WAD.wadExpN(1n)` returns `2 WAD`

## Expected Behavior

`BigInt.WAD.wadExpN(1n)` should return something really close to `1 WAD`

## Steps to Reproduce the Problem

  1. console.log(`BigInt.WAD.wadExpN(1n)`); // should return `1 WAD` but returns `2 WAD`

## Environment

- Version: 6.2.0
- Platform: Mac
- Node.js Version: 20.11.0

**Comment by Rubilmax** [comment]
was badly named, but implementation is good

scale-specific exp is coming
